name: Code Quality Checks

on:
  pull_request:
    branches: [ master ]  # Adjust this with base branch

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  # Adjust this to your PHP version

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run PHP Lint
      run: find . -name "*.php" -not -path "./vendor/*" -print0 | xargs -0 -n1 -P4 php -l

    - name: Run PHPStan
      run: find . -name "*.php" -not -path "./vendor/*" -print0 | xargs -r vendor/bin/phpstan analyse --no-progress
